version: '3.7'
services:
  redis_db:
    image: redis:6.2-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - demo-network
  demo_db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'demo'
      MYSQL_USER: 'demo_user'
      MYSQL_PASSWORD: 'demo'
      MYSQL_ROOT_PASSWORD: 'demo'
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - demo-db:/var/lib/mysql
    networks:
      - demo-network
  demo_app:
    build: .
    environment:
      - DB_URL=jdbc:mysql://demo_db:3306/demo?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
      - DB_USERNAME=demo_user
      - DB_PASSWORD=demo
      - DB_REDIS_URL=redis_db
    ports:
      - "8080:8080"
    depends_on:
      - demo_db
      - redis_db
    restart: on-failure
    networks:
      - demo-network
volumes:
  demo-db:
networks:
  demo-network:
    name: demo-network
    driver: bridge